<?php
    $deptArr = array(
        "Department of Agronomy"
        ,"Department of Genetics and Plant Breeding"
        ,"Department of Horticulture"
        ,"Department of Agricultural Extension and Communication"
        ,"Department of Agricultural Economics"
        ,"Department of Plant Pathology"
        ,"Department of Entomology"
        ,"Department of Soil Science and Agricultural Chemistry"
        ,"Department of Animal Husbandry and Dairying"
        ,"Department of Food, Nutrition and Public Health"
        ,"Department of Textiles and Apparel Designing"
        ,"Department of Human Development and Family Studies"
        ,"Department of Family Resource Management and Consumer Science"
        ,"Department of Extension and Communication Management"
        ,"Department of Agricultural and Rural Development"
        ,"Department of Rural Women's Development"
        ,"Department of Rural Community Development"
        ,"Department of Environment and Community Health"
        ,"Department of Silviculture And Agroforestry"
        ,"Department of Forest Biology, Tree Improvement And Wild Life Sciences"
        ,"Department of Forest Products and Utilization"
        ,"Department of Environmental Sciences and Natural Resource Management"
        ,"Department of Molecular and Cellular Engineering"
        ,"Department of Industrial Microbiology"
        ,"Department of Biochemistry and Biochemical Engineering"
        ,"Department of Computational Biology and Bioinformatics"
        ,"Centre for Tissue Culture Technology"
        ,"Department of Soil and Water Conservation Engineering"
        ,"Department of Farm Machinery and Power Engineering"
        ,"Department of Processing and Food Engineering"
        ,"Department of Irrigation and Drainage Engineering"
        ,"Department of Renewable Energy Engineering"
        ,"Department of Mechanical Engineering"
        ,"Department of Electrical Engineering"
        ,"Department of Computer Science and Information Technology"
        ,"Department of Electronics and Communication Engineering"
        ,"Department of Civil Engineering"
        ,"Centre for Geospatial Technologies"
        ,"Department of Dairy Technology"
        ,"Department of Dairy Engineering"
        ,"Department of Dairy Chemistry"
        ,"Department of Dairy Microbiology"
        ,"Department of Dairy trade and Business Management"
        ,"Pilot Dairy Unit cum Business Process Development Centre"
        ,"Gospel and Plough Institute of Theology"
        ,"Department of Advanced Theological Studies"
        ,"Yeshu Darbar Bible School"
        ,"Department of Business Studies"
        ,"Department of Commerce"
        ,"Department of Anthropology and Social Work"
        ,"Department of English"
        ,"Department of Arts and Social Sciences"
        ,"Department of Teacher Education"
        ,"Department of Physical Education"
        ,"School of Film and Mass Communication"
        ,"Christian College of Nursing"
        ,"Department of Public Health"
        ,"Department of Pharmaceutical Science"
        ,"Department of Clinical Laboratory Science"
        ,"Department of Physiotherapy"
        ,"Department of Radiological Imaging Technology"
        ,"Department of Biological Sciences"
        ,"Department of Physics"
        ,"Department of Chemistry"
        ,"Department of Mathematics and Statistics"
        ,"Department of Forensic Science"
    );
?>